
spring:
  profiles:
    active: local
---
#Program arguments로 job.name 값이 넘어오면 해당 값과 일치하는 Job만 실행
#${job.name:NONE} -> job.name이 있으면 job.name값을 할당하고, 없으면 NONE을 할당
spring.batch.job.names: ${job.name:NONE}
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  profiles: postgres
  datasource:
    hikari:
      maximum-pool-size: 4
    password: pgadmin
    url: jdbc:postgresql://localhost:5432/kalpha
    username: pgadmin
